export function SkipNavigation() {
  return (
    <a
      href="#main-content"
      className="
        fixed
        left-5
        top-5
        z-[1000]
        -translate-y-full
        transform
        rounded-full
        bg-foreground
        px-5
        py-3
        text-sm
        font-semibold
        text-background
        shadow-lg
        transition-transform
        focus-visible:translate-y-0
        focus-visible:outline-none
        focus-visible:ring-2
        focus-visible:ring-ring
        focus-visible:ring-offset-2
        focus-visible:ring-offset-background
        motion-reduce:transition-none
      "
    >
      メインコンテンツへ移動
    </a>
  );
}
