export function SkipNavigation() {
  return (
    <a
      href="#main-content"
      className="
        fixed
        left-4
        top-4
        z-[100]
        -translate-y-24
        rounded-full
        bg-foreground
        px-5
        py-3
        text-sm
        font-semibold
        text-background
        shadow-lg
        transition-transform
        duration-200
        focus-visible:translate-y-0
        focus-visible:outline-none
        focus-visible:ring-2
        focus-visible:ring-ring
        focus-visible:ring-offset-2
        focus-visible:ring-offset-background
      "
    >
      メインコンテンツへ移動
    </a>
  );
}
