import Link from "next/link";
import {
  ArrowLeft,
  Compass,
  Home,
  Search,
} from "lucide-react";

export default function NotFoundPage() {
  return (
    <main
      className="
        relative
        flex
        min-h-screen
        items-center
        justify-center
        overflow-hidden
        bg-background
        px-5
        py-16
        sm:px-8
      "
    >
      <div
        aria-hidden="true"
        className="
          pointer-events-none
          absolute
          -left-32
          -top-32
          size-96
          rounded-full
          bg-secondary/15
          blur-3xl
        "
      />

      <div
        aria-hidden="true"
        className="
          pointer-events-none
          absolute
          -bottom-36
          -right-28
          size-96
          rounded-full
          bg-accent/10
          blur-3xl
        "
      />

      <section
        aria-labelledby="not-found-title"
        className="
          relative
          w-full
          max-w-2xl
          overflow-hidden
          rounded-[2rem]
          border
          border-border/60
          bg-card/90
          p-6
          text-center
          shadow-xl
          shadow-black/5
          backdrop-blur-xl
          sm:rounded-[2.5rem]
          sm:p-10
          lg:p-12
        "
      >
        <div
          className="
            mx-auto
            flex
            size-16
            items-center
            justify-center
            rounded-full
            border
            border-border/55
            bg-secondary/15
            text-foreground
            shadow-sm
          "
        >
          <Compass
            className="size-7"
            strokeWidth={1.7}
            aria-hidden="true"
          />
        </div>

        <p
          className="
            mt-6
            text-xs
            font-semibold
            uppercase
            tracking-[0.25em]
            text-muted-foreground
          "
        >
          Lost in the steam
        </p>

        <h1
          id="not-found-title"
          className="
            mt-3
            text-3xl
            font-semibold
            tracking-[-0.045em]
            text-foreground
            sm:text-4xl
          "
        >
          お探しのページは
          <br className="hidden sm:block" />
          見つかりませんでした
        </h1>

        <p
          className="
            mx-auto
            mt-5
            max-w-lg
            text-sm
            leading-7
            text-muted-foreground
            sm:text-base
            sm:leading-8
          "
        >
          URLが変更されたか、投稿・施設・ユーザー情報が削除された可能性があります。
          ホームや検索から、もう一度目的の場所を探してみてください。
        </p>

        <div
          className="
            mt-8
            grid
            gap-3
            sm:grid-cols-2
          "
        >
          <Link
            href="/"
            className="
              inline-flex
              min-h-12
              items-center
              justify-center
              gap-2
              rounded-full
              bg-primary
              px-6
              text-sm
              font-semibold
              text-primary-foreground
              shadow-sm
              transition
              duration-200
              hover:-translate-y-0.5
              hover:shadow-md
              focus-visible:outline-none
              focus-visible:ring-2
              focus-visible:ring-ring
              focus-visible:ring-offset-2
              focus-visible:ring-offset-background
              active:translate-y-0
            "
          >
            <Home
              className="size-4"
              strokeWidth={1.8}
              aria-hidden="true"
            />

            ホームへ戻る
          </Link>

          <Link
            href="/search"
            className="
              inline-flex
              min-h-12
              items-center
              justify-center
              gap-2
              rounded-full
              border
              border-border
              bg-background/80
              px-6
              text-sm
              font-semibold
              text-foreground
              transition
              duration-200
              hover:-translate-y-0.5
              hover:bg-muted
              focus-visible:outline-none
              focus-visible:ring-2
              focus-visible:ring-ring
              focus-visible:ring-offset-2
              focus-visible:ring-offset-background
              active:translate-y-0
            "
          >
            <Search
              className="size-4"
              strokeWidth={1.8}
              aria-hidden="true"
            />

            施設を探す
          </Link>
        </div>

        <Link
          href="/community"
          className="
            mt-5
            inline-flex
            min-h-10
            items-center
            justify-center
            gap-2
            rounded-full
            px-4
            text-sm
            font-medium
            text-muted-foreground
            transition
            hover:text-foreground
            focus-visible:outline-none
            focus-visible:ring-2
            focus-visible:ring-ring
            focus-visible:ring-offset-2
            focus-visible:ring-offset-background
          "
        >
          <ArrowLeft
            className="size-4"
            strokeWidth={1.8}
            aria-hidden="true"
          />

          Communityを見る
        </Link>

        <p
          className="
            mt-8
            text-xs
            font-medium
            tracking-[0.18em]
            text-muted-foreground/60
          "
        >
          ERROR 404
        </p>
      </section>
    </main>
  );
}
